### ISSUE TITLE
An error about graph-tool

### ISSUE THREAD

**Issue by wenzl1337** [anmartinezs/pyseg_system#5]
When I run pyseg_system/code/tests/tracing_grid.sh, there's an error

./tracing_grid.sh
python ../pyseg/scripts/tests/mcf_synthetic_test.py do_short
/home/wenzl/programs/pyseg_system-master/sys/soft/miniconda2/lib/python2.7/site-packages/graph_tool/all.py:40: RuntimeWarning: Error importing draw module, proceeding nevertheless: /home/wenzl/programs/pyseg_system-master/sys/soft/miniconda2/lib/python2.7/site-packages/graph_tool/draw/libgraph_tool_draw.so: undefined symbol: _ZN5Cairo7Context9show_textERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warnings.warn(msg, RuntimeWarning)
^CTraceback (most recent call last):
  File "../pyseg/scripts/tests/mcf_synthetic_test.py", line 12, in <module>
    from pyseg.scripts import mcf_graph
  File "/home/wenzl/programs/pyseg_system-master/code/pyseg/__init__.py", line 12, in <module>
    import disperse_io
  File "/home/wenzl/programs/pyseg_system-master/code/pyseg/disperse_io/__init__.py", line 11, in <module>
    from disperse_io import *
......

I find there's something wrong with pyseg_system-master/sys/soft/miniconda2/lib/python2.7/site-packages/graph_tool/all.py., which contains a command: from graph_tool.draw import *. As I type this command in python, the same error as above would happen. How can i solve this issue?

**Comment by anmartinezs** [comment]
It seems that graph-tool were not installed properly in your computer, did not you get any error during the installation?

Graph-tool is an external python library, more information about this package in https://graph-tool.skewed.de/

**Comment by wenzl1337** [comment]
When I installed this software, everything seemed OK. There was no error occur and graph_tool was also installed successfully. I removed the whole directory today and installed pyseg again, the same error happened.

**Comment by anmartinezs** [comment]
After installation, are you still getting the next followng error?you had before:
_I find there's something wrong with pyseg_system-master/sys/soft/miniconda2/lib/python2.7/site-packages/graph_tool/all.py., which contains a command: from graph_tool.draw import *. As I type this command in python, the same error as above would happen. How can i solve this issue?_
If this is the case, graph-tool was not installed properly, which computer and OS are you using?

**Comment by wenzl1337** [comment]
ubuntu18.04

**Comment by anmartinezs** [comment]
Have you tried to install graph-tool externally? see the link in a previous
post.
