### ISSUE TITLE
Error when import graph_tool

### ISSUE THREAD

**Issue by ssscj** [anmartinezs/pyseg_system#7]
Hi,
when I run the tests scripts ./tracing_test.py, it says
`/software/anaconda/envs/pyseg/lib/python2.7/site-packages/graph_tool/draw/cairo_draw.py:1494: RuntimeWarning: Error importing Gtk module: No module named gi; GTK+ drawing will not work.`
the final error says 
`IOError: [Errno 2] No such file or directory: 'path/pyseg_software/pyseg_system-master/code/pyseg/scripts/tests/../../../tests//../../data/synthetic_grid/graph_0_it_0/grid_noise_std_0_it_0.pkl'`
and I install the software in Centos system and in anaconda virtual environment.  How can I fix it ? Thank you.

**Comment by ssscj** [comment]
Hi, I find that actually this is two problems. The first one is fixed by installing PyGObject  `pip install PyGObject`
but I can't fix the second problem yet. grid_noise_std_0_it_0.pkl cannot be found yet. Did I miss any step in the manual ?

**Comment by anmartinezs** [comment]
Hi,
You can ignore the first problem, actually this is just a Warning.
Regarding the second one, it seems that either the output folder does not
exist or you don't have writing permission. Create the output folder
manually a try again, please let me know if the problem persists.
Best

**Comment by ssscj** [comment]
Hi,
I created the output folder and still got the same error. The error is like:
`Traceback (most recent call last):
  File "pyseg_software/pyseg_system-master/code/tutorials/synth_sumb/tracing/mb_graph_mp.py", line 305, in <module>
    pr_worker(pr_id,spl_ids[pr_id],q_pkls)
  File "pyseg_software/pyseg_system-master/code/tutorials/synth_sumb/tracing/mb_graph_mp.py", line 200, in pr_worker
    disperse.mse(no_cut=False, inv=False)
  File "pyseg_software/pyseg_system-master/code/pyseg/disperse_io/handler.py", line 362, in mse
    subprocess.call(mse_cmd, stdout=file_log, stderr=file_log)
  File "pyseg_software/pyseg_system-master/sys/soft/miniconda2/envs/pyseg/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "pyseg_software/pyseg_system-master/sys/soft/miniconda2/envs/pyseg/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "pyseg_software/pyseg_system-master/sys/soft/miniconda2/envs/pyseg/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

so I check the code in pyseg/disperse_io/handler.py  line 362 `subprocess.call(mse_cmd, stdout=file_log, stderr=file_log)`
I add `print(mse_cmd)` to see the command and get :
`['mse', './graphs/test_1_tomo_mic_0_bin_2_g1.0.fits', '-mask', './graphs/test_1_tomo_mic_0_bin_2_g1.0_mask.fits', '-dumpManifolds', 'J0a', '-cut', '0.0005', '-downSkl', '-outDir', './graphs/disperse_pr_0']`
And I add `shell = True` and get `subprocess.call(mse_cmd, shell =True, stdout=file_log, stderr=file_log)`
but the software raised an error : mse command not found
So I am still stuck by this problem. Maybe is there anything wrong when I install PySeg ? Thanks for your help.

**Comment by anmartinezs** [comment]
Write mse command on you terminal you should get something like:

martinez@hpcl5006:/> mse
mse version 0.9.24

Usage:
  mse <network filename> [-field <fname>]
      [-outName <fname>] [-noTags] [-outDir <dir>]
      [-periodicity <val>]
      [-mask <fname.ND>[~]]
      [-nthreads <N=$OMP_NUM_THREADS>]

...

If you get a command not found error means that you have not installed DisPerSe properly, most likely because the instalation script of PySeg is tested on Ubuntu but not in CentOS, then you should install DisPerSe manually here you have the link http://www2.iap.fr/users/sousbie/web/html/indexd41d.html

If you manage to install DisPerSe on CentOS please let me know the changes you made so as to have them into accout to make an installer version for CentOS.
